const ROLES = {
  ADMIN: 'admin',
  LOAN_OFFICER: 'loan_officer',
  MANAGER: 'manager',
  CUSTOMER: 'customer',
};

const PERMISSIONS = {
  // User Management
  VIEW_USERS: 'view_users',
  CREATE_USER: 'create_user',
  EDIT_USER: 'edit_user',
  DELETE_USER: 'delete_user',
  ASSIGN_ROLES: 'assign_roles',

  // Loan Management
  CREATE_LOAN: 'create_loan',
  VIEW_OWN_LOANS: 'view_own_loans',
  VIEW_ALL_LOANS: 'view_all_loans',
  EDIT_LOAN: 'edit_loan',
  DELETE_LOAN: 'delete_loan',
  PROCESS_LOAN: 'process_loan',
  APPROVE_LOAN: 'approve_loan',
  REJECT_LOAN: 'reject_loan',

  // Reports
  VIEW_REPORTS: 'view_reports',
  GENERATE_REPORTS: 'generate_reports',

  // Settings
  VIEW_SETTINGS: 'view_settings',
  EDIT_SETTINGS: 'edit_settings',

  // Customer Management
  VIEW_CUSTOMERS: 'view_customers',
  CREATE_CUSTOMER: 'create_customer',
  EDIT_CUSTOMER: 'edit_customer',
  DELETE_CUSTOMER: 'delete_customer',
  VERIFY_KYC: 'verify_kyc',
  ASSESS_RISK: 'assess_risk',

  // Dashboard
  VIEW_ADMIN_DASHBOARD: 'view_admin_dashboard',
  VIEW_OFFICER_DASHBOARD: 'view_officer_dashboard',
  VIEW_MANAGER_DASHBOARD: 'view_manager_dashboard',
  VIEW_CUSTOMER_DASHBOARD: 'view_customer_dashboard',
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.ASSIGN_ROLES,
    PERMISSIONS.CREATE_LOAN,
    PERMISSIONS.VIEW_OWN_LOANS,
    PERMISSIONS.VIEW_ALL_LOANS,
    PERMISSIONS.EDIT_LOAN,
    PERMISSIONS.DELETE_LOAN,
    PERMISSIONS.PROCESS_LOAN,
    PERMISSIONS.APPROVE_LOAN,
    PERMISSIONS.REJECT_LOAN,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.VIEW_OFFICER_DASHBOARD,
    PERMISSIONS.VIEW_MANAGER_DASHBOARD,
    PERMISSIONS.VIEW_CUSTOMER_DASHBOARD,
  ],
  [ROLES.LOAN_OFFICER]: [
    PERMISSIONS.VIEW_ALL_LOANS,
    PERMISSIONS.VIEW_OWN_LOANS,
    PERMISSIONS.CREATE_LOAN,
    PERMISSIONS.EDIT_LOAN,
    PERMISSIONS.PROCESS_LOAN,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_OFFICER_DASHBOARD,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_ALL_LOANS,
    PERMISSIONS.VIEW_OWN_LOANS,
    PERMISSIONS.APPROVE_LOAN,
    PERMISSIONS.REJECT_LOAN,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_MANAGER_DASHBOARD,
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.CREATE_LOAN,
    PERMISSIONS.VIEW_OWN_LOANS,
    PERMISSIONS.VIEW_CUSTOMER_DASHBOARD,
  ],
};

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };
